{  
  "id":"/webapp",
  "dependencies":[  
    "/name",
    "/greeter"
  ],
  "cpus":2,
  "mem":1024,
  "instances":1,
  "container":{  
    "type":"DOCKER",
    "docker":{  
      "image":"arungupta/webapp-service:latest",
      "network":"USER",
      "portMappings":[  
        {  
          "hostPort":0,
          "containerPort":8080,
          "protocol":"tcp"
        }
      ]
    }
  },
  "ipAddress":{  
    "networkName":"dcos"
  },
  "env":{  
    "NAME_SERVICE_HOST":"name.marathon.containerip.dcos.thisdcos.directory",
    "NAME_SERVICE_PORT":"80",
    "NAME_SERVICE_PATH":"/",
    "GREETER_SERVICE_HOST":"greeter.marathon.containerip.dcos.thisdcos.directory",
    "GREETER_SERVICE_PORT":"80",
    "GREETER_SERVICE_HOST":"/"
  },
  "labels":{  
    "HAPROXY_0_VHOST":"dcos-PublicSlaveLo-1B7KS7V0OI0Y6-1504556418.us-west-1.elb.amazonaws.com",
    "HAPROXY_GROUP":"external"
  }
}