version: '3'
services:
  greeter:
    build: ./services/greeter
    image: arungupta/greeter-service:latest
  name:
    build: ./services/name
    image: arungupta/name-service:latest
  webapp:
    build: ./services/webapp
    image: arungupta/webapp-service:latest
    ports:
      - 8080:8080
    depends_on:
      - greeter
      - name
    environment:
      - NAME_SERVICE_HOST=name
      - NAME_SERVICE_PORT=8080
      - NAME_SERVICE_PATH=
      - GREETER_SERVICE_HOST=greeter
      - GREETER_SERVICE_PORT=8080
      - GREETER_SERVICE_PATH=
