version: '3'
services:
  greeter-service:
    build: ./services/greeter
    image: arungupta/greeter-service:latest
  name-service:
    build: ./services/name
    image: arungupta/name-service:latest
  webapp-service:
    build: ./services/webapp
    image: arungupta/webapp-service:latest
    ports:
      - 80:8080
    depends_on:
      - greeter-service
      - name-service
    environment:
      - NAME_SERVICE_HOST=name-service
      - NAME_SERVICE_PORT=8080
      - NAME_SERVICE_PATH=
      - GREETER_SERVICE_HOST=greeter-service
      - GREETER_SERVICE_PORT=8080
      - GREETER_SERVICE_PATH=
